spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fcfs
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
    properties:
      smtp.auth: true
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    test-connection: true
  application:
    name: user-service
---
jwt:
  secret:
    key: ${JWT_SECRET_KEY}
---
encryptor:
  password: ${SYMMETRIC_KEY}
---
server:
  port: 8081
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka